name: Secure Root Repository Deployment
on:
  push:
    branches:
      - '**'

permissions:
  contents: read
  checks: write

jobs:
  root_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Clone Repository Content
        uses: actions/checkout@v5

      - name: Deploy Complete Repo Directly to Live Hosting Channel
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
          channelId: live
          projectId: zaka13
